services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      NODE_ENV: production
      PORT: 4000

      # Base de datos
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      # Stripe
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

    expose:
      - "4000"

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

      args:
        VITE_API_URL: /api
        VITE_UPLOADS_URL: /uploads

    expose:
      - "80"

    depends_on:
      - backend

    restart: unless-stopped